name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy SAM Application to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install AWS SAM CLI
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl -Lo sam-installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip sam-installation.zip -d sam-installation
        sudo ./sam-installation/install
        sam --version

    - name: Delete existing stack if in ROLLBACK_COMPLETE
      run: |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name sam-lambda-stack --query "Stacks[0].StackStatus" --output text || echo "NOT_FOUND")
        if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
          echo "Stack in ROLLBACK_COMPLETE state. Deleting..."
          aws cloudformation delete-stack --stack-name sam-lambda-stack
          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name sam-lambda-stack
        else
          echo "Stack is not in ROLLBACK_COMPLETE state. Proceeding..."
        fi

    - name: Build SAM Application
      run: sam build --template-file sam_lambda/template.yaml

    - name: Deploy SAM Application
      run: sam deploy --no-confirm-changeset --stack-name sam-lambda-stack --capabilities CAPABILITY_IAM --s3-bucket pgr301-couch-explorers-candidate69