name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Sjekker ut koden fra repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Setter opp AWS CLI og SAM CLI
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 # Endre til din region

    # Installerer AWS SAM CLI
    - name: Install or Update AWS SAM CLI
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl -Lo sam-installation.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip sam-installation.zip -d sam-installation
        sudo ./sam-installation/install --update
        sam --version

    # Bygger SAM-applikasjonen
    - name: Build SAM Application
      run: sam build -t sam_lambda/template.yaml

    # Deployerer SAM-applikasjonen
    - name: Deploy SAM Application
      run: |
        sam deploy \
          -t sam_lambda/template.yaml \
          --stack-name my-sam-app \
          --capabilities CAPABILITY_IAM \
          --region eu-west-1 \
          --no-confirm-changeset \
          --parameter-overrides Environment=prod