name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13


      - name: Install SAM CLI and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential
          pip3 install aws-sam-cli

 
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-1
          

      - name: Check working directory
        run: pwd


      - name: Build SAM application
        run: sam build -t  sam_lambda/template.yaml  


      - name: Deploy SAM application
        run: |
          sam deploy -t  sam_lambda/template.yaml --no-confirm-changeset --stack-name main-exam-lambda --capabilities CAPABILITY_IAM